language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-columbia-angular' ]; then cd .. && eval "mv $currentfolder generator-columbia-angular" && cd generator-columbia-angular; fi
